### ISSUE TITLE
Go over new Github README checklist.

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#4]
Created a new GitHub repo template that I want to share in collaborative meetings. 

Included in this is a README template based on a review of README and a need to get agreements on what kinds of information we need. We are prototyping better Github issues templates and READMEs, and a necessary part of that templating process is building consensus and agreements with our collective wisdom.

Will share at our next Docs Lab.

**Comment by chachasikes** [comment]
Adding to next sprint - can close this out or update the template - want to record our process notes

**Comment by chachasikes** [comment]
Moved this into Notion today - it's slowly becoming part of our process.

**Comment by chachasikes** [comment]
Progress update: Process is improving.

Will continue to periodically revise the recommendation with things we are learning for a more perfect government README.

**Comment by xjensen** [comment]
@chachasikes @zakiya Okay to close this issue? Seems like we might be at a point where this can just become a regular part of our work.

**Comment by zakiya** [comment]
@chachasikes Can you add a link to the template you're referencing here? Even if it's still in Notion?

**Comment by chachasikes** [comment]
I will find it, it's probably in Coda already.

**Comment by chachasikes** [comment]
Found it.

Moved the original markdown to Coda in Engineering wiki.

https://coda.io/d/_dL_3_CR2bVn/README-template-DRAFT_sunW_

Next steps:
- [ ] Re-read and revise in Coda (Chach)
- [ ] Include notes on what work went into the template and why (it's not arbitrary)
- [ ] Go over and vet this 
- [ ] Decide on a place to store the template
- [ ] Version the template
- [ ] Add a link to our docs & other engineering resources/templates.
- [ ] Also articulate an editorial process for reviewing and copy editing the template.

**Comment by chachasikes** [comment]
I'll have my revisions to the template done for next bi-weekly meeting.

**Comment by zakiya** [comment]
Did some formatting and light editing to the main [doc.](https://coda.io/d/Engineering-wiki_dL_3_CR2bVn/Guide-to-writing-better-READMEs_sugPb#_luEsO) I think it works as a living document and is a good contender for the Innovation Hub.
